# import

In [ ]:
#Install Pytorch
pip install torch

In [1]:
#import important libraries
import torch
import numpy as np
import matplotlib.pyplot as plt

# Tensor

In [ ]:
  #Scaler
  torch.tensor(4)
  torch.tensor(4/3)
  torch.tensor(4**2)

In [ ]:
#Vector
torch.tensor([1,2,3])

In [ ]:
#Matrix
torch.tensor([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
#Column Vector
torch.tensor([[1],[2],[3]])

In [ ]:
#N-d Tensor
torch.tensor([[[1,2,5],[8,5,6]] ,
              [[5,4,9],[8,8,5]] ,
              [[2,1,7],[9,4,2]]])

In [ ]:
#Data Type
a = torch.tensor([1,2,3] , dtype=torch.float32)
a.dtype

In [ ]:
#Convert
a = a.type(torch.float16)
a.dtype

In [ ]:
#Device
a.device
a = torch.tensor([1,2,3] , device='cuda')
a.device

# **Tensor attribiute and method**

In [ ]:
scaler = torch.tensor(4)
vector = torch.tensor([1,2,3])
matrix = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
tensor = torch.tensor([[[1,2,5],[8,5,6]] ,[[5,4,9],[8,8,5]] ,[[2,1,7],[9,4,2]]])

In [ ]:
#Shape
tensor.shape
#example
c , r , t = tensor.shape
c

In [ ]:
#size
tensor.size(1)

In [ ]:
#min&max
print(tensor.min())
print(tensor.max())

In [ ]:
#mean & std
print(tensor.type(torch.float32).mean())
print(tensor.type(torch.float32).std())

In [ ]:
# Transpose
matrix.t()

# Special Arrays

In [ ]:
#ones
torch.ones((2,3,5,6))

In [ ]:
#zeros
torch.zeros((1,3,5,6))

In [ ]:
#eye
print(torch.eye(5))
print(".............................")
print(torch.eye(5 ,4))


In [ ]:
#empty tensor
em = torch.empty((2,3))
em

In [ ]:
# fill empty tensor
em.fill_(2)
em

In [ ]:
# full
torch.full((2,3) , 1.2)

# Random Arrays

In [ ]:
#rand
torch.rand((2,3)) #between 0 to 1 with equal chance for choose | uniform distribution

In [ ]:
rand_uniform = torch.rand(10000)
plt.hist(rand_uniform);

In [ ]:
#randn
rand_gauss = torch.randn((2,3,3)) #Gussian ditribution | Mean : 0 | std : 1

In [ ]:
#randint
torch.randint(low=0 , high=10 , size=(2,3))

In [ ]:
#randperm
torch.randperm(10)

tensor([0, 1, 6, 8, 5, 4, 2, 3, 7, 9])

# Indexing & Slicing

In [ ]:
#indexing in vector
a = torch.rand(5)
a

In [ ]:
a[3]

In [ ]:
#last element
a[-1]

In [ ]:
#indexing in matrix
b = torch.randn(5 , 3)
b

In [ ]:
b[1,2]

In [ ]:
b[1]

In [ ]:
#indexing in Tensor
c = torch.randint(100 , (4,5,3))
c

In [ ]:
c[0,0,0] , c[2,3,1] , c[3,4,1]

In [ ]:
c[0]

In [ ]:
#slicing in vector
a = torch.rand(10)
a

In [ ]:
a[4:8]

In [ ]:
a[0:1]

In [ ]:
a[0:-1]

In [ ]:
a[-2:-1]

In [ ]:
a[4:]

In [ ]:
a[:3]

In [ ]:
a[::2]

In [ ]:
a[[0 , 2 , 7]]

In [ ]:
#slicing in matrix
b = torch.randn(3 , 5)
b

In [ ]:
b[0:3 , 2:-1]

In [ ]:
b[0:2]

In [ ]:
b[::2 , 2:]

In [ ]:
#slicing in Tensor
c = torch.randn(4,5,7)

In [ ]:
c[1:2 , 3:5 , 2:4]

In [ ]:
c[1]

In [ ]:
c[: , : , -1]

# Math operation

In [ ]:
a = torch.randint(20 , (2,2))
a

tensor([[ 8,  0],
        [12,  1]])

In [ ]:
b = torch.randint(10 , (2,2))
b

tensor([[3, 5],
        [3, 1]])

In [ ]:
#Addition
a + b

tensor([[11,  5],
        [15,  2]])

In [ ]:
#subtraction
a - b

tensor([[ 5, -5],
        [ 9,  0]])

In [ ]:
#multiplication
a * b

tensor([[24,  0],
        [36,  1]])

In [ ]:
#Division
a / b

tensor([[2.6667, 0.0000],
        [4.0000, 1.0000]])

In [ ]:
#infinity
torch.inf

inf

In [ ]:
# Matrix Multiplication
a @ b

tensor([[24, 40],
        [39, 61]])

In [ ]:
# Matrix Multiplication
torch.matmul(a , b)

tensor([[24, 40],
        [39, 61]])

In [ ]:
#broadcasting
a = torch.randint(10 , (1 , 2,2))
print(a)
print("------------------")
print(a + 2)

tensor([[[8, 8],
         [5, 7]]])
------------------
tensor([[[10, 10],
         [ 7,  9]]])


# Dimension Transformation

In [3]:
a = torch.randn(2 , 6)
b = torch.randn(3)

In [ ]:
a

tensor([[ 0.7635,  0.9333, -0.4364,  1.0853, -1.3878,  0.3668],
        [ 1.5489, -0.1653,  1.2090, -0.3599,  1.1365, -1.8732]])

In [ ]:
b

tensor([ 0.2738, -1.4004,  0.1845])

In [ ]:
#View
a.view(2 , 3 , 2)

tensor([[[ 0.7635,  0.9333],
         [-0.4364,  1.0853],
         [-1.3878,  0.3668]],

        [[ 1.5489, -0.1653],
         [ 1.2090, -0.3599],
         [ 1.1365, -1.8732]]])

In [ ]:
#Reshape
a.reshape(2,3,2)

tensor([[[ 0.7635,  0.9333],
         [-0.4364,  1.0853],
         [-1.3878,  0.3668]],

        [[ 1.5489, -0.1653],
         [ 1.2090, -0.3599],
         [ 1.1365, -1.8732]]])

In [ ]:
#N-d Tensor to Vector
a.flatten()

tensor([ 0.7635,  0.9333, -0.4364,  1.0853, -1.3878,  0.3668,  1.5489, -0.1653,
         1.2090, -0.3599,  1.1365, -1.8732])

In [ ]:
#Repeat
b.repeat(3)

tensor([ 0.2738, -1.4004,  0.1845,  0.2738, -1.4004,  0.1845,  0.2738, -1.4004,
         0.1845])

In [ ]:
#Concatnation
torch.cat((a , a))

tensor([[ 0.7635,  0.9333, -0.4364,  1.0853, -1.3878,  0.3668],
        [ 1.5489, -0.1653,  1.2090, -0.3599,  1.1365, -1.8732],
        [ 0.7635,  0.9333, -0.4364,  1.0853, -1.3878,  0.3668],
        [ 1.5489, -0.1653,  1.2090, -0.3599,  1.1365, -1.8732]])

In [ ]:
torch.cat((a , torch.randn(2 , 6) , a))

tensor([[ 0.7635,  0.9333, -0.4364,  1.0853, -1.3878,  0.3668],
        [ 1.5489, -0.1653,  1.2090, -0.3599,  1.1365, -1.8732],
        [-0.0774,  0.9425, -0.8244, -0.3289, -0.7760,  0.7255],
        [ 0.7568,  0.0914, -1.0313, -0.0867,  1.8852, -0.3242],
        [ 0.7635,  0.9333, -0.4364,  1.0853, -1.3878,  0.3668],
        [ 1.5489, -0.1653,  1.2090, -0.3599,  1.1365, -1.8732]])

# Built-in Function

In [7]:
a = torch.randint(10 , (5,))
b = torch.randint(10 , (2 , 2))
c = 10 * torch.rand((3 , 2 , 2))

In [8]:
# Sum
torch.sum(c)

tensor(62.8494)

In [11]:
#cumsum
torch.cumsum(a , 0)

tensor([ 9, 18, 20, 29, 35])

In [12]:
#diff
torch.diff(a)

tensor([ 0, -7,  7, -3])

In [13]:
#prod
torch.prod(a)

tensor(8748)

In [14]:
#sqrt
torch.sqrt(a)

tensor([3.0000, 3.0000, 1.4142, 3.0000, 2.4495])

In [16]:
#std
torch.std(a.type(torch.float32))

tensor(3.0822)

In [17]:
#mean
torch.mean(a.type(torch.float32))

tensor(7.)

In [18]:
#log
torch.log(a.type(torch.float32))

tensor([2.1972, 2.1972, 0.6931, 2.1972, 1.7918])

In [19]:
#max
torch.max(a)

tensor(9)

In [20]:
#argmin
torch.argmin(a)

tensor(2)

In [21]:
#exp
torch.exp(a)

tensor([8.1031e+03, 8.1031e+03, 7.3891e+00, 8.1031e+03, 4.0343e+02])

In [22]:
#variance
torch.var(a.type(torch.float32))

tensor(9.5000)

In [25]:
#topk
#return k values
torch.topk(a , 3 , largest=False)

torch.return_types.topk(
values=tensor([2, 6, 9]),
indices=tensor([2, 4, 1]))

In [26]:
#mode
torch.mode(a)

torch.return_types.mode(
values=tensor(9),
indices=tensor(3))

In [27]:
#median
torch.median(a)

tensor(9)

# torch <--> numpy

In [30]:
a = torch.randperm(5)
b = np.random.randint(0 , 5 , (5))
a ,

(tensor([0, 3, 4, 2, 1]),)

In [32]:
# tensor to numpy
a.numpy()

array([0, 3, 4, 2, 1])

In [33]:
# numpy to tensor
torch.tensor(b , dtype=torch.float32)

tensor([3., 0., 3., 2., 0.])

# Save & Load

In [34]:
# save
torch.save(a , '/content/a.pt')

In [35]:
#Load
torch.load('/content/a.pt')

tensor([0, 3, 4, 2, 1])